admissionhelpdesk/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('home.urls')),
    path('admissionnews/', include('admissionnews.urls')),
    path('modeltest/', include('modeltest.urls')),
    path('calendar/', include('eventcalendar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admissionnews/urls.py
from django.urls import path

from .views import(
    UniversityCreateView, UniversityDetailView,
    UniversityListView, UniversityUpdateView,
    UniversityDeleteView,

    AdmissionNewsCreateView, AdmissionNewsDeleteView,
    AdmissionNewsDetailView, AdmissionNewsUpdateView,
    AdmissionNewsListView,

    CommentCreateView, CommentUpdateView, CommentDeleteView,

    DepartmentCreateView, DepartmentDeleteView, DepartmentDetailView,
    DepartmentUpdateView


)

urlpatterns = [
    path('', UniversityListView.as_view(), name='university-list'),
    path('university/new/', UniversityCreateView.as_view(),
         name='university-create'),
    path('university/<int:pk>/', UniversityDetailView.as_view(),
         name="university-detail"),
    path('university/<int:pk>/update/', UniversityUpdateView.as_view(),
         name="university-update"),
    path('university/<int:pk>/delete/', UniversityDeleteView.as_view(),
         name="university-delete"),
    #
    path('university/<int:pk>/department/new/', DepartmentCreateView.as_view(),name="department-create"),
    path('department/<int:pk>/', DepartmentDetailView.as_view(),name="department-detail"),
    path('department/<int:pk>/update/', DepartmentUpdateView.as_view(),name="department-update"),
    path('department/<int:pk>/delete/', DepartmentDeleteView.as_view(),name="department-delete"),
    #
    path('university/<int:unipk>/new/', AdmissionNewsCreateView.as_view(),
         name="admissionnews-create"),
    path('news/', AdmissionNewsListView.as_view(), name='admissionnews-list'),
    path('news/<int:pk>/', AdmissionNewsDetailView.as_view(),
         name="admissionnews-detail"),
    path('news/<int:pk>/update/', AdmissionNewsUpdateView.as_view(),
         name="admissionnews-update"),
    path('news/<int:pk>/delete/', AdmissionNewsDeleteView.as_view(),
         name="admissionnews-delete"),

    path('news/<int:pk>/comment/new/', CommentCreateView.as_view(), name='comment-create'),
    path('news/comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('news/comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete')

]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home-home'),
]

admissionnews/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image

# Create your models here.


class University(models.Model):
    public = 'Public'
    private = 'Private'
    eng_college = 'Engineering College'
    med_college = 'Medical College'
    type_choice = ((public, 'Public University'),
                   (private, 'Private University'),
                   (eng_college, 'Engineering College'),
                   (med_college, 'Medical College'))
    name = models.CharField(max_length=255)
    website = models.CharField(max_length=255)
    content = models.TextField(default="")
    university_type = models.CharField(max_length=20, choices=type_choice, default=None)
    logo = models.ImageField(default='default.jpg', upload_to='uni_logo')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('university-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super(University, self).save(*args, **kwargs)

        img = Image.open(self.logo.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.logo.path)

class Department(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('department-detail', kwargs={'pk': self.pk})


class AdmissionNews(models.Model):
    title = models.CharField(max_length=512, default='')
    news = models.TextField(default='')
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    date_posted = models.DateTimeField(default=timezone.now)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('admissionnews-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(AdmissionNews, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=512)
    date_commented = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('admissionnews-detail', kwargs={'pk': self.post.pk})


admissionnews/forms.py
from django.forms import ModelForm, DateInput

from .models import Comment, AdmissionNews


class CommentForm(ModelForm):

    class Meta:
        model=Comment
        fields=['comment']



class AdmissionNewsCreateForm(ModelForm):

    class Meta:
        model= AdmissionNews
        fields = ['title', 'news', 'start_time', 'end_time']
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }

    def __init__(self, *args, **kwargs):
        super(AdmissionNewsCreateForm, self).__init__(*args, **kwargs)
        # input_formats parses HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

admissionnews/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse, reverse_lazy
from pprint import pprint
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
    FormView
)
from django.views.generic.edit import FormMixin

from eventcalendar.models import Event
from .models import University, AdmissionNews, Comment, Department
from .forms import CommentForm, AdmissionNewsCreateForm


# Create your views here.


class UniversityListView(ListView):
    model = University
    template = 'admissionnews/university_list.html'
    context_object_name = 'universities'
    ordering = ['name']
    paginate_by = 20


class UniversityDetailView(DetailView):
    model = University

    def get_context_data(self, **kwargs):
        context = super(UniversityDetailView, self).get_context_data(**kwargs)
        uni = University.objects.filter(pk=self.kwargs.get('pk'))[0]
        context['newses'] = AdmissionNews.objects.filter(
            university=uni).order_by('-date_posted')
        return context



class UniversityCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):

    model = University
    fields = ['name', 'website', 'university_type', 'content', 'logo']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_superuser:
            return True
        return False


class UniversityUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):

    model = University
    fields = ['name', 'website', 'university_type', 'content', 'logo']

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        obj =self.get_object()
        if self.request.user.is_superuser or obj.user==self.request.user:
            return True
        return False


class UniversityDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

    model = University


    def test_func(self):
        uni = self.get_object()

        if self.request.user.is_superuser:
            return True
        return False

    def get_success_url(self):
        return reverse('university-list')

class DepartmentCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Department
    fields = ['name']

    def form_valid(self, form):
        form.instance.university = University.objects.filter(pk=self.kwargs.get('pk')).first()
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        return False

class DepartmentDetailView(DetailView):
    model =Department

class DepartmentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Department
    fields = ['name']

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()
        if self.request.user.is_staff or self.request.user.is_superuser or self.request.user==obj.university.user:
            return True
        return False

class DepartmentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Department

    def get_success_url(self):
        return reverse('university-detail', kwargs={'pk':self.object.university.pk})

    def test_func(self):
        obj = self.get_object()
        if self.request.user.is_staff or self.request.user.is_superuser or self.request.user==obj.university.user:
            return True
        return False


class AdmissionNewsListView(ListView):
    model = AdmissionNews
    template = 'admissionnews/admissionnews_list.html'
    context_object_name = 'admissionnewses'
    ordering = ['-date_posted']
    paginate_by = 5


class AdmissionNewsDetailView(FormMixin, DetailView):
    model = AdmissionNews
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(AdmissionNewsDetailView, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        post = AdmissionNews.objects.filter(pk=self.kwargs.get('pk'))[0]
        title = post.title
        description = post.news
        start_time = post.start_time
        end_time = post.end_time
        Event.objects.get_or_create(title=title, description=description, start_time=start_time, end_time=end_time, admissionnews=post)
        context['comments'] = Comment.objects.filter(post=post).order_by('-date_commented')
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = AdmissionNews.objects.filter(
            pk=self.kwargs.get('pk')).first()
        # comment, created = Comment.objects.get_or_create(**form.cleaned_data)
        return super().form_valid(form)

class AdmissionNewsCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = AdmissionNews
    form_class = AdmissionNewsCreateForm

    def form_valid(self, form):
        form.instance.university = University.objects.filter(
            pk=self.kwargs.get('unipk')).first()
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        return False

class AdmissionNewsUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = AdmissionNews
    form_class = AdmissionNewsCreateForm

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        return False


class AdmissionNewsDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = AdmissionNews

    def get_success_url(self):
        return reverse('university-detail', kwargs={'pk':self.object.university.pk})

    def test_func(self):
        if self.request.user.is_superuser or self.request.user.is_staff:
            return True
        return False


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['comment',]

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = AdmissionNews.objects.filter(
            pk=self.kwargs.get('pk')).first()
        return super().form_valid(form)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['comment']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post = AdmissionNews.objects.filter(
            pk=self.kwargs.get('pk')).first()
        return super().form_valid(form)

    def test_func(self):
        obj = self.get_object()

        if self.request.user==obj.user or self.request.user.is_superuser or self.request.user.is_staff:
            return True
        return False

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment

    def get_success_url(self, **kwargs):
        return reverse_lazy('admissionnews-detail', args=(self.object.post.id,))

    def test_func(self):
        obj = self.get_object()

        if self.request.user==obj.user or self.request.user.is_superuser or self.request.user.is_staff:
            return True
        return False

admissionnews/templates/admissionnews/admissionnews_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete University</legend>
            <h2>Are you sure you want to delete the university "{{ object.title }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'admissionnews-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

admissionnews/templates/admissionnews/admissionnews_detail.html
{% extends "home/base.html" %}
{% load  crispy_forms_tags %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'university-list' %}">University-List</a></li>
        <li class="breadcrumb-item"><a href="{% url 'university-detail' object.university.pk %}">{{ object.university.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.title }}</li>
    </ol>
</nav>
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.university.logo.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'university-detail' object.university.pk %}">{{ object.university.name }}</a>
        <a href="{{ object.university.website }}">Official Website</a>
            {% if user.is_superuser or user.is_staff %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'admissionnews-update' object.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'admissionnews-delete' object.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.exam_date }}</p>
        <p class="article-content">{{ object.news }}</p>
    </div>
</article>
{% include 'admissionnews/comment_form.html' %}

{% for comment in comments %}
<font size="-1">
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ comment.user.profile.image.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ comment.user.username }}</a>
            {% if comment.user == request.user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'comment-update' comment.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'comment-delete' comment.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <p class="article-content">{{ comment.comment }}</p>
    </div>
</article>
</font>
{% endfor %}

{% endblock content %}

admissionnews/templates/admissionnews/admissionnews_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Admission News</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

admissionnews/templates/admissionnews/admissionnews_list.html
{% extends "home/base.html" %}
{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
{#        <li class="breadcrumb-item"><a href="{% url 'university-list' %}">University-List</a></li>#}
{#        <li class="breadcrumb-item"><a href="{% url 'university-detail'  %}">{{ object_list.university.name }}</a></li>#}
{#        <li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>#}
    </ol>
</nav>
{% for admissionnews in admissionnewses %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ admissionnews.university.logo.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'university-detail' admissionnews.university.pk %}">{{ admissionnews.university.name }}</a>
            <a href="{{ admissionnews.university.website }}">Official Website</a>
            {% if user.is_superuser or user.is_staff %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'admissionnews-update' admissionnews.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'admissionnews-delete' admissionnews.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <h2><a class="article-title" href="{% url 'admissionnews-detail' admissionnews.id %}">{{ admissionnews.title }}</a></h2>
        <p class="article-content">{{ admissionnews.new }}</p>
    </div>
</article>
{% endfor %}
{% if is_paginated %}

{% if page_obj.has_previous %}
<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
{% endif %}
{% endfor %}

{% if page_obj.has_next %}
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
{% endif %}

{% endif %}
{% endblock content %}

admissionnews/templates/admissionnews/comment_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete Comment</legend>
            <h2>Are you sure you want to delete the comment?</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'admissionnews-detail' object.post.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

admissionnews/templates/admissionnews/comment_form.html
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST" action="{% url 'comment-create' pk=object.pk %}">
        {% csrf_token %}
        <fieldset class="form-group">
{#            <legend class="border-bottom mb-4">Add Comment</legend>#}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Comment</button>
        </div>
    </form>
</div>
{% endblock content %}

admissionnews/templates/admissionnews/department_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <h2>Are you sure you want to delete the department "{{ object.name }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'department-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}
<legend class="border-bottom mb-4">Delete University</legend>

admissionnews/templates/admissionnews/department_detail.html
{% extends "home/base.html" %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'university-list' %}">University-List</a></li>
        <li class="breadcrumb-item"><a href="{% url 'university-detail' object.university.pk %}">{{ object.university.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>
    </ol>
</nav>

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.university.logo.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{% url 'university-detail' object.university.pk %}">{{ object.university.name }}</a>
            {% if user.is_superuser or user.is_staff %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'department-update' object.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'department-delete' object.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.name }}</h2>
    </div>
</article>
    {% if user.is_staff or user.is_superuser %}
<a class="btn btn-outline-info mb-4" href="{% url 'admissionnews-create' unipk=object.university.pk %}">Add Admission News</a>
    {% endif %}
{% for news in object.university.admissionnews_set.all %}
<article class="media content-section">
    <div class="media-body">
        <li>
            <a class="article-title" href="{% url 'admissionnews-detail' news.pk %}">{{ news.title }}</a>
        </li>
    </div>
</article>
{% endfor %}
{% endblock content %}

admissionnews/templates/admissionnews/department_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add Department</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

admissionnews/templates/admissionnews/forbidden.html
{% extends 'home/base.html' %}
{% block content %}
<h1 class="danger ">Access Forbidden</h1>
{% endblock %}

admissionnews/templates/admissionnews/university_confirm_delete.html
{% extends "home/base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Delete University</legend>
            <h2>Are you sure you want to delete the university "{{ object.name }}"</h2>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'university-detail' object.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

admissionnews/templates/admissionnews/university_detail.html
{% extends "home/base.html" %}
{% block content %}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'university-list' %}">University-List</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>
    </ol>
</nav>

<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.logo.url }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ object.university_type }}</a>
        <a href="{{ university.website }}">Official Website</a>
            {% if user.is_staff or user.is_superuser %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'university-update' object.id %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'university-delete' object.id %}">Delete</a>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.name }}</h2>
        <p class="article-content">{{ object.content }}</p>
    </div>
</article>
    {% if user.is_staff or user.is_superuser %}
    <div class="media-body">
<a class="btn btn-outline-info mb-4" href="{% url 'admissionnews-create' unipk=object.id %}">Add Admission News</a>
<a class="btn btn-outline-info mb-4" href="{% url 'department-create' pk=object.id %}">Add Department</a>
    </div>
    {% endif %}
    {% if object.department_set.count != 0  %}
    <div class="list-group-item"><font size="+2" class="article-title"><b>Department List</b></font></br></div>
    {% endif %}
{% for department in object.department_set.all %}
<article class="media content-section">
    <div class="media-body">
        <li>
            <a class="article-title" href="{% url 'department-detail' department.pk %}">{{ department.name }}</a>
        </li>
    </div>
</article>
{% endfor %}
    {% if newses.count != 0  %}
    <div class="list-group-item"><font size="+2" class="article-title"><b>Admission Newses</b></font></br></div>
    {% endif %}
{% for news in newses %}
<article class="media content-section">
    <div class="media-body">
        <li>
            <a class="article-title" href="{% url 'admissionnews-detail' news.pk %}">{{ news.title }}</a>
        </li>
    </div>
</article>
{% endfor %}
{% endblock content %}

admissionnews/templates/admissionnews/university_form.html
{% extends "home/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Add University Entry</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}